### ISSUE TITLE
Create mongo-based database

### ISSUE THREAD

**Issue by atatarov** [omarcompany/prostogram-server#3]
Create mongodb.

The addres can be mongodb://localhost:27017/prostogramdb

Database should have users and cards tables.
User:
1. name - user name, the string from 2 to 30 char's length, requiered field
2. about - user information, the string from 2 to 30 char's, requiered field
3. avatar - url to avatar, the string, requiered field (validation will be in next task)

Card:
1. name - card name,  the string from 2 to 30 char's length, requiered field
2. link - image url, the string,  requiered field
3. owner - link to the author model, the ObjectId, required field
4. likes - like list - array of ObjectId, default - empty array
5. createdAt - created date, type Date, but Number is recomended. Default - Date.now()

**Comment by RostovtsevDanila** [comment]
Мне кажется, лучше будет внутри объекта карточки выделить отдельный объект, у которого будет свойство url. Это даст тебе возможность более гибко менять  дизайн объекта карточки в будущем
И поле name как-то смущает. Мб лучше title?
Типа так
```
{
    title: 'some title', // это имя лучше подойдет для карточки, чем name имхо
    content: {
        url: 'https://lol.kek/cheburek',
        thumbnail: 'https://lol.kek/cheburek_mini',
        geo: 'geo tag', // например
    },
    ....
}
```
А для юзера вместо about мб лучше использовать bio, это как стандарт в соцсетях уж)
Для аватара лучше бы тоже отдельный объект завести, как для image в карточке. 
Еще я не знаю, как у тебя логика будет устроена, но, кажется, что помимо имени нужно что-то типа username, типа как в инсте есть username и title

**Comment by RostovtsevDanila** [comment]
кста контент еще можно разделить на изображение и текст. А изображений вообще может быть несколько
